core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('shop/', include('shop.urls', namespace='shop')),
                  path('users/', include('users.urls', namespace='users'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views

app_name = 'shop'

urlpatterns = [
    path('product/', views.index, name='index'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('products-of-category/<int:category_id>/', views.index, name='products_of_category'),
    path('product-create/', views.product_create, name='product_create'),
    path('product-delete/<int:product_id>/', views.product_delete, name='product_delete'),
    path('product-update/<int:product_id>/', views.product_update, name='product_update'),
    path('comment-view/<int:pk>/', views.comment_view, name='comment_view'),
    path('order-view/<int:pk>/', views.order_view, name='order_view')

]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_page, name='login_page'),
    path('register/', views.register_page, name='register_page'),
    path('logout/', views.logout_page, name='logout_page')
]

shop/models.py
from django.db import models
from decimal import Decimal, getcontext
from django.db.models import Avg
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
    my_order = models.PositiveIntegerField(default=0, null=True, blank=True)

    class Meta:
        abstract = True


class Category(BaseModel):
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'category'
        verbose_name = 'category'
        verbose_name_plural = 'Categories'
        ordering = ['-id']


class Product(BaseModel):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=14, decimal_places=2)
    image = models.ImageField(upload_to='images/', null=True, blank=True, default='images/no_image.png')
    discount = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=1)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', null=True, blank=True)

    @property
    def discounted_price(self):
        if self.discount > 0:
            self.price = self.price * Decimal(1 - self.discount / 100)
        return Decimal(f'{self.price}').quantize(Decimal('0.00'))

    @property
    def comment_rating(self):
        products = self.comments.aggregate(product_avg_rating=Avg('rating'))
        if products['product_avg_rating'] is None:
            return 0
        return Decimal(f'{products['product_avg_rating']}').quantize(Decimal('0.000'))

    @property
    def get_absolute_url(self):
        return self.image.url

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'product'
        ordering = ['my_order']


class Comment(BaseModel):
    class RatingChoice(models.IntegerChoices):
        ONE = 1
        TWO = 2
        THREE = 3
        FOUR = 4
        FIVE = 5

    full_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField()
    content = models.TextField()
    rating = models.PositiveIntegerField(choices=RatingChoice.choices, default=RatingChoice.ONE.value)
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='comments')
    is_private = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.email} => {self.rating} => {self.product.name}'


class Order(BaseModel):
    full_name = models.CharField(max_length=255, null=True, blank=True)
    phone = PhoneNumberField(region='UZ')
    quantity = models.PositiveIntegerField(default=1)
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='orders')

    def __str__(self):
        return f'{self.phone} - {self.product.name}'

shop/forms.py
from django import forms

from shop.models import Product, Category, Comment, Order
from phonenumber_field.formfields import PhoneNumberField


# Form vs ModelForm

#
# class ProductForm(forms.Form):
#     name = forms.CharField(max_length=200)
#     description = forms.CharField(widget=forms.Textarea)
#     price = forms.DecimalField(max_digits=14, decimal_places=2)
#     image = forms.ImageField(required=False)
#     quantity = forms.IntegerField(required=False)
#     category = forms.ModelChoiceField(queryset=Category.objects.all())
#     discount = forms.IntegerField(required=False, min_value=0, max_value=100)
#     rating = forms.ChoiceField(choices=Product.RatingChoice)
#
#     def save(self, commit=True):
#         cd = self.cleaned_data
#         product = None
#         if commit:
#             product = Product.objects.create(
#                 name=cd.get('name'),
#                 description=cd.get('description'),
#                 price=cd.get('price'),
#                 image=cd.get('image'),
#                 quantity=cd.get('quantity'),
#                 category=cd.get('category'),
#                 discount=cd.get('discount'),
#                 rating=cd.get('rating')
#             )
#         return product


class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ()


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('product',)


class OrderModelForm(forms.ModelForm):
    phone = PhoneNumberField(region='UZ')

    class Meta:
        model = Order
        exclude = ('product',)

shop/views.py
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from shop.models import Product, Category
from shop.forms import ProductModelForm, CommentModelForm, OrderModelForm
from django.db.models import Avg


# Create your views here.


def index(request, category_id: int | None = None):
    search_query = request.GET.get('q', '')
    categories = Category.objects.all()
    filter_query = request.GET.get('filter', '')

    if category_id:
        products = Product.objects.filter(category_id=category_id)
    else:
        products = Product.objects.all().order_by('-updated_at')  # select * from products order by updated_at DESC

    if search_query:
        products = Product.objects.filter(Q(name__icontains=search_query) | Q(description__icontains=search_query))

    if filter_query == 'expensive':
        products = products.order_by('-price')

    elif filter_query == 'cheap':
        products = products.order_by('price')

    elif filter_query == 'rating':
        products = products.annotate(rating_avg=Avg('comments__rating')).order_by('-rating_avg')

    context = {
        'products': products,
        'categories': categories
    }
    return render(request, 'shop/home.html', context)


def product_detail(request, product_id):
    categories = Category.objects.all()
    product = get_object_or_404(Product, id=product_id)
    related_products = Product.objects.all().annotate(rating_avg=Avg('comments__rating')).filter(
        category=product.category).exclude(id=product.id).order_by('-rating_avg')
    comments = product.comments.all()
    context = {
        'product': product,
        'categories': categories,
        'comments': comments,
        'related_products': related_products
    }
    return render(request, 'shop/detail.html', context)


# @login_required(login_url='/admin/')
# def product_create(request):
#     form = ProductModelForm()
#     if request.method == 'POST':
#         form = ProductModelForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('index')
#
#     context = {
#         'form': form
#     }
#     return render(request, 'shop/product-create.html', context)

@login_required(login_url='/admin/')
def product_create(request):
    form = ProductModelForm()
    if request.method == 'POST':
        form = ProductModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            return redirect('index')

    context = {
        'form': form,
        'action': 'Create'
    }
    return render(request, 'shop/product-create.html', context)


@login_required(login_url='/admin/')
def product_update(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    form = ProductModelForm(instance=product)
    if request.method == 'POST':
        form = ProductModelForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('product_detail', product_id)
    context = {
        'product': product,
        'form': form,
        'action': 'Update'
    }
    return render(request, 'shop/product-update.html', context)


@login_required(login_url='/admin/')
def product_delete(request, product_id):
    product = Product.objects.get(id=product_id)
    if product:
        product.delete()
        return redirect('index')
    return render(request, 'shop/detail.html', {'product': product})


def comment_view(request, pk):
    product = Product.objects.get(id=pk)
    form = CommentModelForm()
    if request.method == 'POST':
        form = CommentModelForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            rating = request.POST.get('rating')
            print(type(rating))
            comment.rating = rating
            comment.product = product
            comment.save()
            return redirect('product_detail', product.id)

    context = {
        'form': form,
        'product': product
    }

    return render(request, 'shop/detail.html', context)


def order_view(request, pk):
    product = Product.objects.get(id=pk)
    form = OrderModelForm()
    if request.method == 'POST':
        form = OrderModelForm(request.POST)
        quantity = int(request.POST.get('quantity'))
        if form.is_valid():
            if product.quantity >= quantity:
                order = form.save(commit=False)
                order.product = product
                product.quantity = product.quantity - quantity
                product.save()
                order.save()
                # message success
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Order successfully created'
                )
                return redirect('product_detail', product.id)
            else:
                # error message
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Something is wrong'
                )
    return render(request, 'shop/detail.html', {'form': form, 'product': product})

shop/templates/shop/base/base.html
{% load register_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'shop/assets/favicon.ico' %}"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'shop/css/styles.css' %}" rel="stylesheet"/>
</head>
<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'shop:index' %}">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'shop:index' %}">All Products</a></li>
                        <li>
                            <hr class="dropdown-divider"/>
                        </li>
                        {% for category in categories %}
                            <li><a class="dropdown-item"
                                   href="{% url 'shop:products_of_category' category.id %}">{{ category.title }}</a>
                            </li>
                        {% endfor %}

                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <input type="text" name="q" class="form-contro">
                <button class="btn btn-outline-dark" type="submit">
                    <i class="bi-search-fill me-1"></i>
                    Search

                </button>
            </form>

            {% if user.is_authenticated %}
                <form method="post" action="{% url 'users:logout_page' %}">
                    {% csrf_token %}
                    <div class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">

                        <button type="submit" class="btn btn-danger">Logout</button>

                    </div>
                    {{ user.email }}
                </form>

            {% else %}

                <div class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <a href="{% url 'users:login_page' %}">
                        <button type="button" class="btn btn-primary">Login</button>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
</nav>
<!-- Header-->
{% block home_content %}
{% endblock %}

{% block product_detail_content %}
{% endblock %}


{% block product_create_content %}
{% endblock %}

{% block product_update_content %}
{% endblock %}
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'shop/js/scripts.js' %}"></script>
</body>
</html>