core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('shop/', include('shop.urls', namespace='shop')),
                  path('users/', include('users.urls', namespace='users'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views

app_name = 'shop'

urlpatterns = [
    path('product/', views.index, name='index'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('products-of-category/<int:category_id>/', views.index, name='products_of_category'),
    path('product-create/', views.product_create, name='product_create'),
    path('product-delete/<int:product_id>/', views.product_delete, name='product_delete'),
    path('product-update/<int:product_id>/', views.product_update, name='product_update'),
    path('comment-view/<int:pk>/', views.comment_view, name='comment_view'),
    path('order-view/<int:pk>/', views.order_view, name='order_view')

]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_page, name='login_page'),
    path('register/', views.register_page, name='register_page'),
    path('logout/', views.logout_page, name='logout_page')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumber, PhoneNumberField
from users.managers import CustomUserManager


# Create your models here.


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)
    phone_number = PhoneNumberField(region='UZ')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ValidationError
from django.forms import PasswordInput

from users.apps import UsersConfig
from users.models import CustomUser


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=PasswordInput)

    # def clean_email(self):
    #     email = self.cleaned_data['email']
    #     if not CustomUser.objects.filter(email=email).exists():
    #         raise ValidationError(f'That {email} not found.')
    #     return email
    #
    # def clean_password(self):
    #     password = self.cleaned_data['password']
    #     if not CustomUser.objects.filter(password=password).exists():
    #         raise ValidationError(f'Password did not match')
    #
    # # def clean_password(self):
    # #     password = self.cleaned_data['password']
    # #     if password:
    # #         raise ValidationError(f'Passwords do not match.')
    # #     return password
    #
    # def clean(self):
    #     cleaned_data = super().clean()  # Muhim! Formadagi barcha ma'lumotlarni olish
    #     email = cleaned_data.get("email")
    #     password = cleaned_data.get("password")
    #
    #     if not email or not password:
    #         raise forms.ValidationError("Username or password invalid")
    #
    #     return cleaned_data

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.shortcuts import render, redirect
from users.forms import LoginForm
from users.models import CustomUser

# Create your views here.


def login_page(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, email=cd['email'], password=cd['password'])
            if user:
                if user.is_active:
                    login(request, user)
                    return redirect('shop:index')
                else:
                    messages.add_message(
                        request,
                        messages.ERROR,
                        'Disabled account'
                    )
                    return render(request, 'users/login.html')
            else:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Username or Password invalid'
                )
                return render(request, 'users/login.html')

    return render(request, 'users/login.html', {'form': form})

def register_page(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data


            if CustomUser.objects.filter(email=cd['email']).exists():
                messages.error(request, 'Account with this email already exists.')
            else:
                # Create user
                user = CustomUser.objects.create_user(
                    email=cd['email'],
                    password=cd['password']
                )
                user.save()
                messages.success(request, 'You have successfully registered')
                login(request, user)
                return redirect('shop:index')

    return render(request, 'users/register.html', {'form': form})

def logout_page(request):
    if request.method == 'POST':
        logout(request)
        return redirect('shop:index')

users/templates/users/login.html
{% extends 'users/base/base.html' %}
{% load static %}

{% block title %} Login Page{% endblock %}

{% block login_content %}
    <main class="main" id="top">
        <div class="container-fluid">
            <div class="row min-vh-100 flex-center g-0">
                <div class="col-lg-8 col-xxl-5 py-3 position-relative"><img class="bg-auth-circle-shape"
                                                                            src="{% static 'users/assets/img/icons/spot-illustrations/bg-shape.png' %}"
                                                                            alt="" width="250"><img
                        class="bg-auth-circle-shape-2"
                        src="{% static 'users/assets/img/icons/spot-illustrations/shape-1.png' %}"
                        alt=""
                        width="150">
                    <div class="card overflow-hidden z-index-1">
                        <div class="card-body p-0">
                            <div class="row g-0 h-100">
                                <div class="col-md-5 text-center bg-card-gradient">
                                    <div class="position-relative p-4 pt-md-5 pb-md-7 light">
                                        <div class="bg-holder bg-auth-card-shape"
                                             style="background-image:url({% static 'users/assets/img/icons/spot-illustrations/half-circle.png' %});">
                                        </div>
                                        <!--/.bg-holder-->

                                        <div class="z-index-1 position-relative"><a
                                                class="link-light mb-4 font-sans-serif fs-4 d-inline-block fw-bolder"
                                                href="{% url 'shop:index' %}">falcon</a>
                                            <p class="opacity-75 text-white">With the power of Falcon, you can now focus
                                                only on functionaries for your digital products, while leaving the UI
                                                design
                                                on us!</p>
                                        </div>
                                    </div>
                                    <div class="mt-3 mb-4 mt-md-4 mb-md-5 light">
                                        <p class="text-white">Don't have an account?<br><a
                                                class="text-decoration-underline link-light"
                                                href="{% url 'users:register_page' %}">Get started!</a>
                                        </p>
                                        <p class="mb-0 mt-4 mt-md-5 fs--1 fw-semi-bold text-white opacity-75">Read our
                                            <a
                                                    class="text-decoration-underline text-white" href="#!">terms</a> and
                                            <a
                                                    class="text-decoration-underline text-white"
                                                    href="#!">conditions </a></p>
                                    </div>
                                </div>
                                <div class="col-md-7 d-flex flex-center">
                                    <div class="p-4 p-md-5 flex-grow-1">
                                        <div>
                                            {% if messages %}
                                                <ul class="messages">
                                                    {% for message in messages %}
                                                        <li style="color:red;" {% if message.tags %}
                                                            class="{{ message.tags }}"{% endif %}>{{ message }}
                                                        </li>
                                                    {% endfor %}
                                                </ul>
                                            {% endif %}
                                            {% if form.errors %}
                                                <div class="alert alert-warning alert-dismissible fade show"
                                                     role="alert">
                                                    <p class="m-0">{{ form.errors }}</p>
                                                    <button type="button"
                                                            class="btn-close"
                                                            data-bs-dismiss="alert"
                                                            aria-label="Close">
                                                    </button>
                                                </div>
                                            {% endif %}
                                        </div>
                                        <div class="row flex-between-center">
                                            <div class="col-auto">
                                                <h3>Account Login</h3>
                                            </div>
                                        </div>
                                        <form method="post" action="{% url 'users:login_page' %}">
                                            {% csrf_token %}
                                            <div class="mb-3">
                                                <label class="form-label" for="card-email">Email address</label>
                                                <input class="form-control" name="email" id="card-email" type="email"/>
                                            </div>
                                            <div class="mb-3">
                                                <div class="d-flex justify-content-between">
                                                    <label class="form-label" for="card-password">Password</label>
                                                </div>
                                                <input class="form-control" name="password" id="card-password"
                                                       type="password"/>
                                            </div>
                                            <div class="row flex-between-center">
                                                <div class="col-auto">
                                                    <div class="form-check mb-0">
                                                        <input class="form-check-input" type="checkbox"
                                                               id="card-checkbox"
                                                               checked="checked"/>
                                                        <label class="form-check-label mb-0" for="card-checkbox">Remember
                                                            me</label>
                                                    </div>
                                                </div>
                                                <div class="col-auto"><a class="fs--1"
                                                                         href="../../../pages/authentication/card/forgot-password.html">Forgot
                                                    Password?</a></div>
                                            </div>
                                            <div class="mb-3">
                                                <button class="btn btn-primary d-block w-100 mt-3" type="submit"
                                                        name="submit">Log in
                                                </button>
                                            </div>
                                        </form>
                                        <div class="position-relative mt-4">
                                            <hr class="bg-300"/>
                                            <div class="divider-content-center">or log in with</div>
                                        </div>
                                        <div class="row g-2 mt-2">
                                            <div class="col-sm-6"><a
                                                    class="btn btn-outline-google-plus btn-sm d-block w-100"
                                                    href="#"><span
                                                    class="fab fa-google-plus-g me-2" data-fa-transform="grow-8"></span>
                                                google</a></div>
                                            <div class="col-sm-6"><a
                                                    class="btn btn-outline-facebook btn-sm d-block w-100"
                                                    href="#"><span class="fab fa-facebook-square me-2"
                                                                   data-fa-transform="grow-8"></span>
                                                facebook</a></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base/base.html' %}

{% block title %} Register Page{% endblock %}

{% block register_content %}
    <main class="main" id="top">
        <div class="container-fluid">
            <div class="row min-vh-100 flex-center g-0">
                <div class="col-lg-8 col-xxl-5 py-3 position-relative"><img class="bg-auth-circle-shape"
                                                                            src="../../../assets/img/icons/spot-illustrations/bg-shape.png"
                                                                            alt="" width="250"><img
                        class="bg-auth-circle-shape-2" src="../../../assets/img/icons/spot-illustrations/shape-1.png"
                        alt=""
                        width="150">
                    <div class="card overflow-hidden z-index-1">
                        <div class="card-body p-0">
                            <div class="row g-0 h-100">
                                <div class="col-md-5 text-center bg-card-gradient">
                                    <div class="position-relative p-4 pt-md-5 pb-md-7 light">
                                        <div class="bg-holder bg-auth-card-shape"
                                             style="background-image:url(../../../assets/img/icons/spot-illustrations/half-circle.png);">
                                        </div>
                                        <!--/.bg-holder-->

                                        <div class="z-index-1 position-relative"><a
                                                class="link-light mb-4 font-sans-serif fs-4 d-inline-block fw-bolder"
                                                href="../../../index.html">falcon</a>
                                            <p class="opacity-75 text-white">With the power of Falcon, you can now focus
                                                only on functionaries for your digital products, while leaving the UI
                                                design
                                                on us!</p>
                                        </div>
                                    </div>
                                    <div class="mt-3 mb-4 mt-md-4 mb-md-5 light">
                                        <p class="pt-3 text-white">Have an account?<br><a
                                                class="btn btn-outline-light mt-2 px-4"
                                                href="{% url 'users:login_page' %}">Log In</a></p>
                                    </div>
                                </div>
                                <div class="col-md-7 d-flex flex-center">
                                    <div class="p-4 p-md-5 flex-grow-1">
                                        <h3>Register</h3>
                                        <form method="post">
                                            {% csrf_token %}
                                            <div class="mb-3">
                                                <label class="form-label" for="card-name">Name</label>
                                                <input class="form-control" name="name" type="text" autocomplete="on"
                                                       id="card-name"/>
                                            </div>
                                            <div class="mb-3">
                                                <label class="form-label" for="card-email">Email address</label>
                                                <input class="form-control" name="email" type="email" autocomplete="on"
                                                       id="card-email"/>
                                            </div>
                                            <div class="row gx-2">
                                                <div class="mb-3 col-sm-6">
                                                    <label class="form-label" for="card-password">Password</label>
                                                    <input class="form-control" name="password" type="password" autocomplete="on"
                                                           id="card-password"/>
                                                </div>
                                                <div class="mb-3 col-sm-6">
                                                    <label class="form-label" for="card-confirm-password">Confirm
                                                        Password</label>
                                                    <input class="form-control" name="confirm_password" type="password" autocomplete="on"
                                                           id="card-confirm-password"/>
                                                </div>
                                                <div class="mb-3 col-sm-6">
                                                    {% if messages %}
                                                <ul class="messages">
                                                    {% for message in messages %}
                                                        <li style="color:red;" {% if message.tags %}
                                                            class="{{ message.tags }}"{% endif %}>{{ message }}
                                                        </li>
                                                    {% endfor %}
                                                </ul>
                                            {% endif %}
                                                </div>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox"
                                                       id="card-register-checkbox"/>
                                                <label class="form-label" for="card-register-checkbox">I accept the <a
                                                        href="#!">terms </a>and <a href="#!">privacy policy</a></label>
                                            </div>
                                            <div class="mb-3">
                                                <button class="btn btn-primary d-block w-100 mt-3" type="submit"
                                                        name="submit">Register
                                                </button>
                                            </div>
                                        </form>
                                        <div class="position-relative mt-4">
                                            <hr class="bg-300"/>
                                            <div class="divider-content-center">or register with</div>
                                        </div>
                                        <div class="row g-2 mt-2">
                                            <div class="col-sm-6"><a
                                                    class="btn btn-outline-google-plus btn-sm d-block w-100"
                                                    href="#"><span
                                                    class="fab fa-google-plus-g me-2" data-fa-transform="grow-8"></span>
                                                google</a></div>
                                            <div class="col-sm-6"><a
                                                    class="btn btn-outline-facebook btn-sm d-block w-100"
                                                    href="#"><span class="fab fa-facebook-square me-2"
                                                                   data-fa-transform="grow-8"></span>
                                                facebook</a></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}