core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('shop/', include('shop.urls', namespace='shop')),
                  path('users/', include('users.urls', namespace='users'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views

app_name = 'shop'

urlpatterns = [
    path('product/', views.index, name='index'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('products-of-category/<int:category_id>/', views.index, name='products_of_category'),
    path('product-create/', views.product_create, name='product_create'),
    path('product-delete/<int:product_id>/', views.product_delete, name='product_delete'),
    path('product-update/<int:product_id>/', views.product_update, name='product_update'),
    path('comment-view/<int:pk>/', views.comment_view, name='comment_view'),
    path('order-view/<int:pk>/', views.order_view, name='order_view')

]

shop/models.py
from django.db import models
from decimal import Decimal, getcontext
from django.db.models import Avg
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
    my_order = models.PositiveIntegerField(default=0, null=True, blank=True)

    class Meta:
        abstract = True


class Category(BaseModel):
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'category'
        verbose_name = 'category'
        verbose_name_plural = 'Categories'
        ordering = ['-id']


class Product(BaseModel):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=14, decimal_places=2)
    image = models.ImageField(upload_to='images/', null=True, blank=True, default='images/no_image.png')
    discount = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=1)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', null=True, blank=True)

    @property
    def discounted_price(self):
        if self.discount > 0:
            self.price = self.price * Decimal(1 - self.discount / 100)
        return Decimal(f'{self.price}').quantize(Decimal('0.00'))

    @property
    def comment_rating(self):
        products = self.comments.aggregate(product_avg_rating=Avg('rating'))
        if products['product_avg_rating'] is None:
            return 0
        return Decimal(f'{products['product_avg_rating']}').quantize(Decimal('0.000'))

    @property
    def get_absolute_url(self):
        return self.image.url

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'product'
        ordering = ['my_order']


class Comment(BaseModel):
    class RatingChoice(models.IntegerChoices):
        ONE = 1
        TWO = 2
        THREE = 3
        FOUR = 4
        FIVE = 5

    full_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField()
    content = models.TextField()
    rating = models.PositiveIntegerField(choices=RatingChoice.choices, default=RatingChoice.ONE.value)
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='comments')
    is_private = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.email} => {self.rating} => {self.product.name}'


class Order(BaseModel):
    full_name = models.CharField(max_length=255, null=True, blank=True)
    phone = PhoneNumberField(region='UZ')
    quantity = models.PositiveIntegerField(default=1)
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='orders')

    def __str__(self):
        return f'{self.phone} - {self.product.name}'

shop/forms.py
from django import forms

from shop.models import Product, Category, Comment, Order
from phonenumber_field.formfields import PhoneNumberField


# Form vs ModelForm

#
# class ProductForm(forms.Form):
#     name = forms.CharField(max_length=200)
#     description = forms.CharField(widget=forms.Textarea)
#     price = forms.DecimalField(max_digits=14, decimal_places=2)
#     image = forms.ImageField(required=False)
#     quantity = forms.IntegerField(required=False)
#     category = forms.ModelChoiceField(queryset=Category.objects.all())
#     discount = forms.IntegerField(required=False, min_value=0, max_value=100)
#     rating = forms.ChoiceField(choices=Product.RatingChoice)
#
#     def save(self, commit=True):
#         cd = self.cleaned_data
#         product = None
#         if commit:
#             product = Product.objects.create(
#                 name=cd.get('name'),
#                 description=cd.get('description'),
#                 price=cd.get('price'),
#                 image=cd.get('image'),
#                 quantity=cd.get('quantity'),
#                 category=cd.get('category'),
#                 discount=cd.get('discount'),
#                 rating=cd.get('rating')
#             )
#         return product


class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ()


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('product',)


class OrderModelForm(forms.ModelForm):
    phone = PhoneNumberField(region='UZ')

    class Meta:
        model = Order
        exclude = ('product',)

shop/views.py
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from shop.models import Product, Category
from shop.forms import ProductModelForm, CommentModelForm, OrderModelForm
from django.db.models import Avg


# Create your views here.


def index(request, category_id: int | None = None):
    search_query = request.GET.get('q', '')
    categories = Category.objects.all()
    filter_query = request.GET.get('filter', '')

    if category_id:
        products = Product.objects.filter(category_id=category_id)
    else:
        products = Product.objects.all().order_by('-updated_at')  # select * from products order by updated_at DESC

    if search_query:
        products = Product.objects.filter(Q(name__icontains=search_query) | Q(description__icontains=search_query))

    if filter_query == 'expensive':
        products = products.order_by('-price')

    elif filter_query == 'cheap':
        products = products.order_by('price')

    elif filter_query == 'rating':
        products = products.annotate(rating_avg=Avg('comments__rating')).order_by('-rating_avg')

    context = {
        'products': products,
        'categories': categories
    }
    return render(request, 'shop/home.html', context)


def product_detail(request, product_id):
    categories = Category.objects.all()
    product = get_object_or_404(Product, id=product_id)
    related_products = Product.objects.all().annotate(rating_avg=Avg('comments__rating')).filter(
        category=product.category).exclude(id=product.id).order_by('-rating_avg')
    comments = product.comments.all()
    context = {
        'product': product,
        'categories': categories,
        'comments': comments,
        'related_products': related_products
    }
    return render(request, 'shop/detail.html', context)


# @login_required(login_url='/admin/')
# def product_create(request):
#     form = ProductModelForm()
#     if request.method == 'POST':
#         form = ProductModelForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('index')
#
#     context = {
#         'form': form
#     }
#     return render(request, 'shop/product-create.html', context)

@login_required(login_url='/admin/')
def product_create(request):
    form = ProductModelForm()
    if request.method == 'POST':
        form = ProductModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            return redirect('index')

    context = {
        'form': form,
        'action': 'Create'
    }
    return render(request, 'shop/product-create.html', context)


@login_required(login_url='/admin/')
def product_update(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    form = ProductModelForm(instance=product)
    if request.method == 'POST':
        form = ProductModelForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('product_detail', product_id)
    context = {
        'product': product,
        'form': form,
        'action': 'Update'
    }
    return render(request, 'shop/product-update.html', context)


@login_required(login_url='/admin/')
def product_delete(request, product_id):
    product = Product.objects.get(id=product_id)
    if product:
        product.delete()
        return redirect('index')
    return render(request, 'shop/detail.html', {'product': product})


def comment_view(request, pk):
    product = Product.objects.get(id=pk)
    form = CommentModelForm()
    if request.method == 'POST':
        form = CommentModelForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            rating = request.POST.get('rating')
            print(type(rating))
            comment.rating = rating
            comment.product = product
            comment.save()
            return redirect('product_detail', product.id)

    context = {
        'form': form,
        'product': product
    }

    return render(request, 'shop/detail.html', context)


def order_view(request, pk):
    product = Product.objects.get(id=pk)
    form = OrderModelForm()
    if request.method == 'POST':
        form = OrderModelForm(request.POST)
        quantity = int(request.POST.get('quantity'))
        if form.is_valid():
            if product.quantity >= quantity:
                order = form.save(commit=False)
                order.product = product
                product.quantity = product.quantity - quantity
                product.save()
                order.save()
                # message success
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Order successfully created'
                )
                return redirect('product_detail', product.id)
            else:
                # error message
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Something is wrong'
                )
    return render(request, 'shop/detail.html', {'form': form, 'product': product})

shop/templates/shop/detail.html
{% extends 'shop/base/base.html' %}
{% load static %}
{% load register_tags %}

{% block title %}
    Product Detail
{% endblock %}

{% block product_detail_content %}
    <section class="py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-items-center">
                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ product.get_absolute_url }}"
                                           alt="..."/></div>
                <div class="col-md-6">
                    <div>
                        {% if user.is_authenticated %}
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                                    data-bs-target="#deleteModal">
                                Delete
                            </button>
                            <!-- Delete Confirmation Modal -->
                            <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="deleteModalLabel">Confirm Deletion</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                        </div>
                                        <form method="post" action="{% url 'shop:product_delete' product.id %}">

                                            <div class="modal-body">
                                                Are you sure you want to delete <strong>{{ product.name }}</strong>?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                                                    Cancel
                                                </button>
                                                {% csrf_token %}
                                                <button type="submit" class="btn btn-danger">Yes, Delete</button>
                                            </div>
                                        </form>

                                    </div>
                                </div>
                            </div>

                            <a href="{% url 'shop:product_update' product.id %}">
                                <button type="button" class="btn btn-outline-warning">Update</button>
                            </a>
                        {% endif %}
                    </div>
                    <div class="small mb-1"><h3>Quantity : {{ product.quantity }}</h3></div>
                    <h1 class="display-5 fw-bolder">{{ product.name }}</h1>
                    <div class="fs-5 mb-5">
                        {% if product.discount %}
                            <span class="text-muted text-decoration-line-through">
                                    ${{ product.price }}
                                    </span>
                            ${{ product.discounted_price }}
                        {% else %}
                            ${{ product.price }}
                        {% endif %}
                    </div>
                    <p class="lead">{{ product.description }}</p>
                    <div class="d-flex">
                        <form method="post" action="{% url 'shop:order_view' product.id %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <h2>Place an order</h2>
                            </div>
                            <div class="form-group mb-3">
                                <label for="formGroupExampleInput">Your name</label>
                                <input type="text" class="form-control" name="full_name" placeholder="Your name">
                            </div>
                            <div class="form-group mb-3">
                                <label for="formGroupExampleInput2">Your phone</label>
                                <input type="text" name="phone" class="form-control" placeholder="Your phone">
                            </div>
                            <div class="form-group mb-3">
                                {% if form.phone.errors %}
                                    <div class="text-danger">
                                        {{ form.phone.errors }}
                                    </div>
                                {% endif %}


                            </div>
                            <div class="form-group mb-3">
                                <label for="formGroupExampleInput2">Quantity</label>
                                <input type="number" name="quantity" class="form-control" placeholder="Quantity">
                            </div>


                            <div class="form-group mb-3">

                                <input type="submit" class="btn btn-success" value="Send">
                            </div>
                            <div class="form-group mb-3">

                                {% if messages %}
                                    <div class="messages">
                                        {% for message in messages %}
                                            <div class="alert {% if message.tags == 'success' %}alert-success{% elif message.tags == 'error' %}alert-danger{% endif %}">
                                                {{ message }}
                                            </div>
                                        {% endfor %}
                                    </div>
                                {% endif %}

                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="container mt-4 mb-4">
        <div class="row">
            <div class="col-12">
                <div class="text-center">
                    <h2>Latest comments ({{ product.comments.count }})</h2>
                </div>
                {% for comment in comments %}
                    <div class="media card p-4 mt-2">
                        <div class="media-body">

                            <div class="d-flex justify-content-lg-start small text-warning mb-2">
                                {#                                    {% with ''|center:product.rating as range %}#}
                                {#                                        {% for f in range %}#}
                                {#                                            <div class="bi-star-fill"></div>#}
                                {#                                        {% endfor %}#}
                                {#                                    {% endwith %}#}
                                {% for _ in comment.rating|get_range %}
                                    <div class="bi-star-fill"></div>
                                {% endfor %}

                            </div>

                            <h3 class="mt-0">{{ comment.full_name }}</h3>
                            <p>{{ comment.content }}</p>
                            <h5>{{ comment.created_at }}</h5>
                        </div>
                    </div>
                {% endfor %}


            </div>

            <div class="col-8 offset-2 mt-5">

                <div class=" p-5">
                    <div class="text-center">
                        <h3>Add Comment</h3>
                    </div>

                    <form method="post" action="{% url 'shop:comment_view' product.id %}">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                            <label for="rating">Rating:</label>
                            <select id="rating" name="rating">
                                <option value="1">⭐ (1)</option>
                                <option value="2">⭐⭐ (2)</option>
                                <option value="3">⭐⭐⭐ (3)</option>
                                <option value="4">⭐⭐⭐⭐ (4)</option>
                                <option value="5">⭐⭐⭐⭐⭐ (5)</option>
                            </select>
                        </div>
                        <div class="form-group mb-3">
                            <label for="formGroupExampleInput">Your name</label>
                            <input type="text" class="form-control" name="full_name" placeholder="Your name">
                        </div>
                        <div class="form-group mb-3">
                            <label for="formGroupExampleInput2">Your email</label>
                            <input type="email" name="email" class="form-control" placeholder="Your email">
                        </div>

                        <div class="form-group mb-3">
                            <label for="formGroupExampleInput2">Your comment</label>
                            <textarea name="content" class="form-control" id="" cols="30" rows="10"></textarea>
                        </div>

                        <div class="form-group mb-3">

                            <input type="submit" class="btn btn-success" value="Send">
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>
    <!-- Related items section-->
    <section class="py-5 bg-light">
        <div class="container px-4 px-lg-5 mt-5">
            <h2 class="fw-bolder mb-4">Related products</h2>
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for product in related_products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            {% if product.discount %}
                                <div class="badge bg-dark text-white position-absolute"
                                     style="top: 0.5rem; right: 0.5rem">
                                    Sale
                                </div>
                            {% endif %}
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.get_absolute_url }}" alt="..."/>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.name }}</h5>
                                    <!-- Product reviews-->
                                    <div>
                                        <h5>rating : {{ product.comment_rating }}</h5>
                                    </div>
                                    <!-- Product price-->
                                    {% if product.discount %}
                                        <span class="text-muted text-decoration-line-through">
                                    ${{ product.price }}
                                    </span>
                                        ${{ product.discounted_price }}
                                    {% else %}
                                        ${{ product.price }}
                                    {% endif %}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                                            href="{% url 'shop:product_detail' product.id %}">View
                                    product</a></div>


                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section>
{% endblock %}

shop/templates/shop/home.html
{% extends 'shop/base/base.html' %}

{% load static %}


{% block title %}Home Page{% endblock %}


{% block home_content %}
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Shop in style</h1>
                <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
            </div>
        </div>
    </header>
    <!-- Section-->

    <div class="container mt-5">
        <div class="text-left">
            <h3>Filter by</h3>
        </div>
        <div class="row">
            <div class="col-1">
                <a class="btn btn-outline-dark mt-auto" href="?filter=expensive"> Expensive </a>
            </div>

            <div class="col-1">
                <a class="btn btn-outline-dark mt-auto" href="?filter=cheap"> Cheap </a>
            </div>

            <div class="col-1">
                <a class="btn btn-outline-dark mt-auto" href="?filter=rating"> Rating </a>
            </div>
            {% if user.is_superuser %}
                <div class="col-1">
                    <a href="{% url 'shop:product_create' %}">
                        <button type="submit" class="btn btn-outline-success">
                            Add Product
                        </button>
                    </a>
                </div>
            {% endif %}

        </div>
    </div>
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for product in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            {% if product.discount %}
                                <div class="badge bg-dark text-white position-absolute"
                                     style="top: 0.5rem; right: 0.5rem">
                                    Sale
                                </div>
                            {% endif %}
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.get_absolute_url }}" alt="..."/>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.name }}</h5>
                                    <!-- Product reviews-->
                                    <div>
                                        <h5>rating : {{ product.comment_rating }}</h5>
                                    </div>
                                    <!-- Product price-->
                                    {% if product.discount %}
                                        <span class="text-muted text-decoration-line-through">
                                    ${{ product.price }}
                                    </span>
                                        ${{ product.discounted_price }}
                                    {% else %}
                                        ${{ product.price }}
                                    {% endif %}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                                            href="{% url 'shop:product_detail' product.id %}">View
                                    product</a></div>


                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section>
{% endblock %}

shop/templates/shop/product-create.html
{% extends 'shop/base/base.html' %}

{% block product_create_content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-lg">
                    <div class="card-header bg-primary text-white text-center">
                        <h4>Product {{ action }}</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data" action="{% url 'shop:product_create' %}">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="text-center">
                                <button type="submit" class="btn btn-success">{{ action }}</button>
                                <a href="{% url 'shop:index' %}">
                                    <button type="button" class="btn btn-secondary">Back to Dashboard</button>
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}

shop/templates/shop/product-update.html
{% extends 'shop/base/base.html' %}


{% block product_update_content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-lg">
                    <div class="card-header bg-primary text-white text-center">
                        <h4>Product {{ action }}</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data"
                              action="{% url 'shop:product_update' product.id %}">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="text-center">
                                <button type="submit" class="btn btn-success">{{ action }}</button>
                                <a href="{% url 'shop:index' %}">
                                    <button type="button" class="btn btn-secondary">Back to Dashboard</button>
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}